routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// убрать на продакшне
// Artisan::call('view:clear');

/** synchronization **/

Route::get('sync/send', 'SynchronizationController@send');
Route::any('sync/receive', 'SynchronizationController@receive');
Route::get('sync/request', 'BackwardSyncController@request');
Route::get('sync/response', 'BackwardSyncController@response');

Route::middleware('maintenance')->group(function () {
	Route::prefix('instructors')
		->namespace('Instructors')
		->name('instructors.')
		->group(base_path('routes/instructors.php'));

	/** user public **/
	Route::get('rent', 'PublicController@index')->name('public.index');
	Route::post('rent/calculate', 'PublicController@calculate')->name('public.calculate');
	Route::get('rent/locations', 'PublicController@getLocations')->name('public.locations');
	Route::post('rent', 'PublicController@store')->name('public.store');
	Route::get('rent/{onlineOrder}/process', 'PublicController@process')->name('public.process');
	Route::get('rent/{onlineOrder}/success', 'PublicController@success')->name('public.success');

	Route::post('login/barcode', 'BarcodeLogin@handle')->name('login.barcode');
	Auth::routes();

	Route::prefix('test')->group(function () {
		Route::get('schedule', 'TestController@schedule');
		Route::get('api', 'TestController@api');
	});

	Route::resource('guest', 'GuestController');
	Route::post('guest/find', 'GuestController@find')->name('guest.find');
	Route::get('clients/{client}/barcode', 'ClientController@barcode')->name('clients.barcode');
	Route::post('clients/{client}/ajax', 'ClientController@ajaxUpdate')->name('clients.ajax.update');

	Route::get('/expired_passports/upload', 'ExpiredPassportController@upload')->name('expired_passports.upload');
	Route::post('/expired_passports/check', 'ExpiredPassportController@check')->name('expired_passports.check');


	// сканер штрихкодов
	Route::middleware('api_login')->group(function () {
		Route::get('/atol_status/request', 'AtolStatusController@request')->name('atol.status.request');
		Route::get('/atol_status/{uuid}', 'AtolStatusController@ping')->name('atol.status.ping');
		Route::get('/scan/refund', 'ScannerController@refund')->name('scanner.refund');
		Route::get('/scan/set_price', 'ScannerController@setPrice')->name('scanner.set_price');
		Route::get('/scan/set_price_extra', 'ScannerController@setPriceExtra')->name('scanner.set_price_extra');
		Route::get('/scan/client', 'ScannerController@client')->name('scanner.client');
		Route::get('/scan/unit', 'ScannerController@unit')->name('scanner.unit');
		Route::get('/scan/update', 'ScannerController@updateOrder')->name('scanner.update');
		Route::get('/scan/order', 'ScannerController@order')->name('scanner.order');
		Route::get('/scan/create_order', 'ScannerController@createOrder')->name('scanner.create_order');
		Route::get('/scan/cancel_order', 'ScannerController@cancelOrder')->name('scanner.cancel_order');
		Route::get('/scan/promocode', 'ScannerController@promocode')->name('scanner.promocode');
		Route::get('/scan/pay', 'ScannerController@pay')->name('scanner.pay');
		Route::get('/scan/force_pay', 'ScannerController@forcePay')->name('scanner.force_pay');
		Route::get('/scan/pay_extra', 'ScannerController@payExtra')->name('scanner.pay_extra');
		Route::get('/scan/print_receipt', 'ScannerController@printReceipt')->name('scanner.print_receipt');
		Route::get('/scan/end', 'ScannerController@end')->name('scanner.end');
		Route::get('/scan/group', 'ScannerController@addToGroup')->name('scanner.add_to_group');
		Route::get('/scan/ungroup', 'ScannerController@removeFromGroup')->name('scanner.remove_from_group');
		Route::get('/scan/replace', 'ScannerController@replace')->name('scanner.replace');
		Route::get('/scan/get_clients', 'ScannerController@getClients')->name('scanner.get_clients');
		Route::get('/scan/update_condition', 'ScannerController@updateCondition')->name('scanner.update_condition');
	});

	Route::middleware('auth')->group(function () {

		Route::get('/', function () {
			return redirect()->route('dashboard.index');
		});

		Route::resource('roles', 'RoleController');
		Route::resource('permissions', 'PermissionController');

		Route::middleware('location_active')->group(function () {
			// вебкамера
			Route::post('webcam', 'ClientController@webcam')->name('client.webcam');
			Route::post('clients/webcam/{client}', 'ClientController@webcamSave')->name('client.webcam_save');

			Route::get('synchronizations', 'SynchronizationController@index')->name('synchronizations.index');

			// смены
			Route::get('shifts/{id}/report', 'ShiftController@report')->name('shifts.report');
			Route::get('shifts', 'ShiftController@index')->name('shifts.index');
			Route::get('shifts/open', 'ShiftController@open')->name('shifts.open');
			Route::get('shifts/xreport', 'ShiftController@xreport')->name('shifts.xreport');
			Route::get('shifts/{id}', 'ShiftController@close')->name('shifts.close');

			Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard.index');
			Route::get('analytics', 'DashboardController@analytics')->name('analytics.index');

			// настройки
			Route::get('settings', 'SettingsController@edit')->name('settings.edit');
			Route::post('settings', 'SettingsController@update')->name('settings.update');

			// категории
			Route::resource('categories', 'CategoryController');

			// бренды
			Route::resource('brands', 'BrandController');

			// крепления
			Route::resource('bindings', 'BindingController');

			// агенты
			Route::get('agents/{id}/restore', 'AgentController@restore')->name('agents.restore');
			Route::resource('agents', 'AgentController');

			// пользователи
			Route::get('users/{id}/restore', 'UserController@restore')->name('users.restore');
			Route::resource('users', 'UserController');
			Route::get('users/{id}/barcode', 'UserController@barcode')->name('users.barcode');

			// модели
			Route::resource('products', 'ProductController');

			// филиалы
			Route::resource('locations', 'LocationController');

			// прейскуранты
			Route::resource('price_lists', 'PriceListController');
			Route::post('price_lists/{price_list}/timeline', 'PriceListController@timeline')->name('price_lists.timeline');


			// клиенты
			Route::get('clients/json', 'ClientController@json')->name('clients.json');
			Route::resource('clients', 'ClientController');

			// заказы
			Route::resource('orders', 'OrderController');
			Route::get('orders/{order}/agreement', 'OrderController@agreement')->name('agreement');
			Route::get('orders/{order}/barcode', 'OrderController@barcode');
			Route::get('orders/{order}/sticker', 'OrderController@sticker');
			Route::get('orders/{order}/pledge', 'OrderController@pledgeAgreement');


			// склад
			Route::get('stock/json', 'StockController@json')->name('stock.json');
			Route::get('stock/import', 'StockController@import')->name('stock.import');
			Route::post('stock/import', 'StockController@import');
			Route::get('stock/is_unique', 'StockController@checkIfUnitUnique')->name('stock.is_unique');
			Route::resource('stock', 'StockController');

			// массовое редактирование
			Route::get('massediting', 'MassEditingController@index')->name('massediting.index');
			Route::post('massediting', 'MassEditingController@store')->name('massediting.store');
			Route::post('massediting/units', 'MassEditingController@getUnits')->name('massediting.get_units');
			Route::post('massediting/unit', 'MassEditingController@getUnit')->name('massediting.get_unit');

			// инвентаризация
			Route::get('stocktaking/perform', 'StocktakingController@perform')->name('stocktaking.perform');
			Route::get('stocktaking/{stocktaking}', 'StocktakingController@show')->name('stocktaking.show');
			Route::get('stocktaking', 'StocktakingController@index')->name('stocktaking.index');
			Route::post('stocktaking', 'StocktakingController@store')->name('stocktaking.store');
			Route::post('stocktaking/units', 'StocktakingController@getUnits')->name('stocktaking.get_units');
			Route::post('stocktaking/unit', 'StocktakingController@getUnit')->name('stocktaking.get_unit');

			// отчеты
			Route::get('reports/daily_revenue', 'ReportController@daily_revenue')->name('reports.financial');
			Route::get('reports/agreements', 'ReportController@agreements')->name('reports.agreements');
			Route::get('reports/agent_sales_common', 'ReportController@agent_sales_common')->name('reports.agent_sales_common');
			Route::get('reports/agent_sales_detailed', 'ReportController@agent_sales_detailed')->name('reports.agent_sales_detailed');

			Route::get('reports/inventory_rent', 'ReportController@inventory_rent')->name('reports.inventory_rent');
			Route::get('reports/inventory_stock', 'ReportController@inventory_stock')->name('reports.inventory_stock');
			Route::get('reports/inventory_stock_detailed', 'ReportController@inventory_stock_detailed')->name('reports.inventory_stock_detailed');
			Route::get('reports/inventory_sale', 'ReportController@inventory_sale')->name('reports.inventory_sale');
			Route::get('reports/inventory_history', 'ReportController@inventory_history')->name('reports.inventory_history');

			Route::get('reports/inventory_products', 'ReportController@inventory_products')->name('reports.inventory_products');
			Route::get('reports/products_sale', 'ReportController@products_sale')->name('reports.products_sale');
			Route::get('reports/bookings', 'ReportController@bookings')->name('reports.bookings');
			Route::get('reports/effectivity', 'ReportController@effectivity')->name('reports.effectivity');

app/Http/Controllers/Instructors/CalendarController.php
<?php

namespace App\Http\Controllers\Instructors;

use App\Http\Controllers\Controller;
use App\Instructors\Event;
use App\Instructors\Service;
use App\Instructors\Category;
use App\Instructors\Location;
use App\User;
use Illuminate\Http\Request;

class CalendarController extends Controller
{
	public function __construct()
	{
		$this->middleware(['role:superadmin|admin|manager|operator|trainer']);
	}

	public function index(Request $request)
	{
		// manager@crm.promokod.fun

		$categories = Category::all();

		$categories->map(function ($category) {
			if($category->id === Category::SKI)
			{
				$category->icon = '/images/ski.png';
			}
			else if($category->id === Category::SNOWBOARD)
			{
				$category->icon = '/images/board.png';
			}
		});

		if (auth()->user()->hasRole('trainer|manager'))
			return view('instructors.calendar.index', compact('categories'));

		$services = Service::all();
		$locations = Location::all();
		
		$currentLocation = null;

		if ($request->has('location'))
		{
			$managers = auth()->user()->role('manager')
				->where('location_id', $request->location)->get();
			$trainers = auth()->user()->role('trainer')
				->where('location_id', $request->location)->get();
			$currentLocation = Location::find($request->location);
		}
		else
		{
			$managers = auth()->user()->role('manager')->get();
			$trainers = auth()->user()->role('trainer')->get();
		}

		return view('instructors.calendar.index', compact(
			'services',
			'categories',
			'locations',
			'managers',
			'trainers',
			'currentLocation'
		));
	}

	public function event($id)
	{
		$event = Event::find($id);
		return view('instructors.calendar.event', compact('event'));
	}

	public function resources_json(Request $request)
	{
		$category_id = isset($request->category_id) ? $request->category_id : 1;
		$user = auth()->user();

		$output = [];

		if($user->hasRole('trainer')) {
			$output[] = [
				'id' => $user->id,
				'title' => $user->full_name,
				'category_id' => $user->category_id,
				'location_id' => $user->location_id,
			];
		}
		else {
			$trainers = User::role('trainer')->where('category_id', $category_id);

			if($user->hasRole('manager')) {
				$trainers = $trainers = $user->location->trainers()->role('trainer')->where('category_id', $category_id);
			}
			
			$trainers = $trainers->get();
			foreach($trainers as $trainer) {
				$output[] = [
					'id' => $trainer->id,
					'title' => $trainer->full_name,
					'category_id' => $trainer->category_id,
					'location_id' => $trainer->location_id 
				];
			}
		}

		return response()->json($output);
	}

	public function events_json(Request $request)
	{
		$services = Service::all();

		$where = [
			//['event_date', '>=', explode('T', $request->start)[0]],
			//['event_date', '<=', explode('T', $request->end)[0]]
		];

		$user = auth()->user();

		if ($user->hasRole('trainer'))
		{
			$where[] = ['trainer_id', $user->id];
		}
		/*
		elseif ($user->hasRole('manager'))
		{
			$where[] = ['location_id', $user->location_id];
		}
		*/
		else
		{
			if ($request->location !== null)
				$where[] = ['location_id', $request->location];

			if ($request->manager !== null)
				$where[] = ['manager_id', $request->manager];

			if ($request->trainer !== null)
				$where[] = ['trainer_id', $request->trainer];
		}

		$events = Event::where($where)->get();

		$output = [];

		foreach ($events as $event)
		{
			$output[] = [
				'id' => $event->id,
				'resourceId' => $event->trainer_id,
				'title' => $services->find($event->service_id)->name,
				'start' => $event->event_date->format('Y-m-d').'T'.$event->start_time,
				'end' => $event->event_date->format('Y-m-d').'T'.$event->end_time,
				'url' => '/instructors/calendar/'.$event->id.'/event'
			];
		}

		return json_encode($output);
	}
}

app/Http/Controllers/Instructors/CategoryController.php
<?php

namespace App\Http\Controllers\Instructors;

use App\Http\Controllers\Controller;
use App\Instructors\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
	public function __construct()
	{
		$this->middleware(['role:superadmin|admin']);
	}

	public function index()
	{
		$categories = Category::all();

		return view('instructors.category.index', compact('categories'));
	}

	public function create()
	{
		return view('instructors.category.create');
	}

	public function store(Request $request, Category $category)
	{
		request()->validate([
			'name' => 'required|string|max:100'
		]);

		$category->create($request->all());

		return redirect()->route('instructors.category.index')->with('success', 'Категория успешно создана');
	}

	public function show($id)
	{
		//
	}

	public function edit(Category $category)
	{
		return view('instructors.category.edit', compact('category'));
	}

	public function update(Request $request, Category $category)
	{
		request()->validate([
			'name' => 'required|string|max:100'
		]);

		$category->update($request->all());

		return redirect()->route('instructors.category.index')->with('success', 'Категория успешно сохранена');
	}

	public function destroy($id)
	{
		Category::destroy($id);

		return redirect()->route('instructors.category.index')->with('success', 'Категория удалена');
	}
}

app/Http/Controllers/Instructors/ClientController.php
<?php

namespace App\Http\Controllers\Instructors;

use App\Http\Controllers\Controller;
use App\Instructors\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;

class ClientController extends Controller
{
	public function __construct()
	{
		$this->middleware(['role:superadmin|admin|manager|operator']);
	}

	public function index()
	{
		return view('instructors.clients.index');
	}

	public function clients_json(Request $request)
	{
		$columns = Schema::getColumnListing('clients');

		$clients = Client::where([])
						->orderBy(
							$columns[$request->order[0]['column']],
							$request->order[0]['dir']
						);


		if ($request->search['value'] !== null)
		{
			foreach ($columns as $column)
				$clients->orWhere($column, 'like', '%'.$request->search['value'].'%');
		}

        $filteredCount = $clients->count();
        
		$clients = $clients->offset($request->start)
            ->limit($request->length)
            ->get();

		$output = [];

		foreach ($clients as $client)
		{
			$output[] = [
				$client->id,
				$client->last_name.' '.$client->first_name.' '.$client->mid_name,
				$client->phone,
				$client->email,
				$client->created_at->format('d.m.Y H:i'),
				$client->updated_at->format('d.m.Y H:i')
			];
		}

		return json_encode([
			'draw' => $request->draw,
			'recordsTotal' => Client::count(),
			'recordsFiltered' => $filteredCount,
			'data' => $output
		]);
	}

	public function create()
	{
		return view('instructors.clients.create');
	}

	public function store(Request $request)
	{
		request()->validate([
			'last_name'   => 'required|string|max:50',
			'first_name'  => 'required|string|max:50',
			'mid_name'    => 'required|string|max:50'
		]);

		$client = Client::create($request->except('ajax'));

		if($request->ajax)
		{
			return response()->json([
				'success' => true,
				'name' => $client->full_name,
				'id' => $client->id
			]);
		}
		return redirect()->route('instructors.clients.index', $client)
			->with('success', 'Клиент успешно добавлен');
	}

	public function show()
	{
		//
	}

	public function edit(Client $client)
	{
		return view('instructors.clients.edit', compact('client'));
	}

	public function update(Request $request, Client $client)
	{
		request()->validate([
			'last_name'   => 'required|string|max:50',
			'first_name'  => 'required|string|max:50',
			'mid_name'    => 'required|string|max:50'
		]);

		$client->update($request->all());

		return redirect()->route('instructors.clients.index', $client)
			->with('success', 'Данные успешно сохранены');
	}

	public function destroy(Client $client)
	{
		$client->delete();

		return redirect()->route('instructors.clients.index')->with('success', 'Клиент удален');
	}
}

resources/views/instructors/modals/cashier.blade.php
<!-- barcode modal -->
<div class="modal fade" id="cashierPopup" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document" style="max-width: 800px;">
        <div class="modal-content bg-white">
            <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td>Имя</td>
                                        <td id="cashier_popup_full_name"></td>
                                    </tr>
                                    <tr>
                                        <td>Телефон</td>
                                        <td id="cashier_popup_phone"></td>
                                    </tr>
                                    <tr>
                                        <td>Договор</td>
                                        <td>
                                            <div class="badge badge-primary float-right ml-1 p-2" id="cashier_popup_group"></div>
                                            <div class="badge float-right p-2" id="cashier_popup_status"></div>
                                            <select class="form-control form-control-sm" id="cashier_popup_order_id" style="max-width: 140px;">
                                            </select> 
                                        </td>
                                    </tr>
                                </tbody>
                            </table>       
                        </div>
                    </div>

                    <hr />

                    <form name="cashier">
                        <div class="row">
                            <div class="form-group col-12">
                                <label>Способ оплаты</label>
                                <label class="float-right">
                                    <input type="checkbox" id="cashier_popup_kkt"> ККТ
                                </label>
                                <select class="form-control" id="cashier_popup_paid_by">
                                    <option value="cash">Наличные</option>
                                    <option value="card">Карта</option>
                                </select>
                            </div>
                        </div>
                    </form>

                    <div class="row">
                        <div class="col-12">
                            <div class="card border-primary border">
                                <div class="card-body p-3 text-center">
                                    К оплате:
                                    <div id="cashier_popup_price">0</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr />

                    <button id="cashier_popup_pay" type="button" class="btn btn-outline-primary">Оплачено</button>
                    <button id="cashier_popup_agreement" type="button" class="btn btn-outline-info">Договор</button>
                    <button id="cashier_popup_end" type="button" class="btn btn-outline-success">Завершить</button>

                    <hr />

                    <h5>
                    Текущий заказ
	                </h5>
	                <table id="order_table_cashier" class="table table-bordered">
	                    <thead>
	                        <tr>
	                            <th>Артикул</th>
	                            <th>Категория</th>
	                            <th>Наименование</th>
	                            <th>Стоимость</th> 
	                            <th>Размер</th>
	                        </tr>
	                    </thead>
	                </table>

            </div>
        </div>
    </div>
</div>
<!-- endbarcode modal -->

resources/views/instructors/modals/create_client.blade.php
<div class="modal fade" id="createClientModal" tabindex="-1" role="dialog" aria-labelledby="createClientModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createClientModalLabel">Новый клиент</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body pb-0 pt-0">
                <form method="post" action="{{ route('instructors.clients.store') }}" id="create_client_form" name="create_client">
                    @csrf
                    <input type="hidden" name="ajax" value="1">
                    <div class="row">
                        <div class="form-group col-6">
                            <label class="col-form-label">Фамилия</label>
                            <input type="text" class="form-control" name="last_name" required autofocus>
                        </div>
            
                        <div class="form-group col-6">
                            <label class="col-form-label">Имя</label>
                            <input type="text" class="form-control" name="first_name" required>
                        </div>
            
                        <div class="form-group col-6">
                            <label class="col-form-label">Отчество</label>
                            <input type="text" class="form-control" name="mid_name" required>
                        </div>
            
                        <div class="form-group col-6">
                            <label class="col-form-label">Номер телефона</label>
                            <input type="text" class="form-control" name="phone" required>
                        </div>
            
                        <div class="form-group col-6">
                            <label class="col-form-label">Email</label>
                            <input type="text" class="form-control" name="email">
                        </div>
            
                        <div class="form-group col-6">
                            <label class="col-form-label">Номер паспорта</label>
                            <input type="text" class="form-control" name="passport">
                        </div>
            
                        <div class="form-group col-12">
                            <label class="col-form-label">Заметка</label>
                            <textarea class="form-control" name="description"></textarea>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="$('#create_client_form').submit();">Создать</button>
                <button type="button" class="btn btn-light" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

resources/views/instructors/modals/event.blade.php
<!-- barcode modal -->
@push('js')
<script>

</script>
@endpush

<div class="modal fade" id="eventPopup" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document" style="max-width: 800px;">
        <div class="modal-content bg-white">
            <div class="modal-body">

            	<form action="{{ route('instructors.event.pay', $event) }}" method="post">
            		@csrf
	            	<div class="form-group">
		            	<table id="event_table_cashier" class="table table-bordered">
		                    <thead>
		                        <tr>
		                            <th>Тренер</th>
		                            <th>Дата</th>
		                            <th>Время начала</th>
		                            <th>Время окончания</th>
		                        </tr>
		                    </thead>
		                    <tbody>
		                    	<tr>
		                    		<td>
		                    			{{ $event->trainer->full_name }}
		                    		</td>
		                    		<td>
		                    			{{ $event->event_date->format('d.m.Y') }}
		                    		</td>
		                    		<td>
		                    			{{ $event->start_time }}
		                    		</td>
		                    		<td>
		                    			{{ $event->end_time }}
		                    		</td>
		                    	</tr>
		                    </tbody>
		                </table>
		            </div>

	                <div class="row mb-2">
	                	<div class="col-6 text-center">
	                		<h3 style="line-height: 5rem;">
	                			СУММА К ОПЛАТЕ
	                		</h3>
	                	</div>

	                	<div class="col-6">
		                	<div class="card border-primary border">
		                        <div class="card-body p-3 text-center">
		                            <h1 id="event_popup_price" class="mb-0">
		                            	{{ $event->cost }}
		                            </h1>
		                        </div>
		                    </div>
		                </div>
	                </div>

	                <div class="row mb-4">
	                	<div class="col-6">
	                		<button class="btn btn-primary btn-block" id="event_popup_paid_by_cash" type="button">Наличные</button>
	                	</div>
	                	<div class="col-6">
	                		<button class="btn btn-outline-success btn-block" id="event_popup_paid_by_card" type="button">Банковская карта</button>
	                	</div>
	                </div>

	                <input type="hidden" name="paid_by" value="cash" id="event_popup_paid_by">
	                <input type="hidden" id="event_popup_kkt"> 

	                <div class="row" id="amountContainer">
	                	<div class="form-group col-6">
	                		<label><h4>ВНЕСЕНО</h4></label>
	                		<input type="text" class="form-control" id="event_popup_amount">
	                	</div>
	                	<div class="form-group col-6">
	                		<label><h4>СДАЧА</h4></label>
	                		<input type="text" class="form-control" id="event_popup_change" disabled>
	                	</div>
	                </div>

	                <button id="event_popup_pay" class="btn btn-outline-primary">Оплатить</button>
	            </form>
            </div>
        </div>
    </div>
</div>
<!-- endbarcode modal -->