routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// убрать на продакшне
// Artisan::call('view:clear');

/** synchronization **/

Route::get('sync/send', 'SynchronizationController@send');
Route::any('sync/receive', 'SynchronizationController@receive');
Route::get('sync/request', 'BackwardSyncController@request');
Route::get('sync/response', 'BackwardSyncController@response');

Route::middleware('maintenance')->group(function () {
	Route::prefix('instructors')
		->namespace('Instructors')
		->name('instructors.')
		->group(base_path('routes/instructors.php'));

	/** user public **/
	Route::get('rent', 'PublicController@index')->name('public.index');
	Route::post('rent/calculate', 'PublicController@calculate')->name('public.calculate');
	Route::get('rent/locations', 'PublicController@getLocations')->name('public.locations');
	Route::post('rent', 'PublicController@store')->name('public.store');
	Route::get('rent/{onlineOrder}/process', 'PublicController@process')->name('public.process');
	Route::get('rent/{onlineOrder}/success', 'PublicController@success')->name('public.success');

	Route::post('login/barcode', 'BarcodeLogin@handle')->name('login.barcode');
	Auth::routes();

	Route::prefix('test')->group(function () {
		Route::get('schedule', 'TestController@schedule');
		Route::get('api', 'TestController@api');
	});

	Route::resource('guest', 'GuestController');
	Route::post('guest/find', 'GuestController@find')->name('guest.find');
	Route::get('clients/{client}/barcode', 'ClientController@barcode')->name('clients.barcode');
	Route::post('clients/{client}/ajax', 'ClientController@ajaxUpdate')->name('clients.ajax.update');

	Route::get('/expired_passports/upload', 'ExpiredPassportController@upload')->name('expired_passports.upload');
	Route::post('/expired_passports/check', 'ExpiredPassportController@check')->name('expired_passports.check');


	// сканер штрихкодов
	Route::middleware('api_login')->group(function () {
		Route::get('/atol_status/request', 'AtolStatusController@request')->name('atol.status.request');
		Route::get('/atol_status/{uuid}', 'AtolStatusController@ping')->name('atol.status.ping');
		Route::get('/scan/refund', 'ScannerController@refund')->name('scanner.refund');
		Route::get('/scan/set_price', 'ScannerController@setPrice')->name('scanner.set_price');
		Route::get('/scan/set_price_extra', 'ScannerController@setPriceExtra')->name('scanner.set_price_extra');
		Route::get('/scan/client', 'ScannerController@client')->name('scanner.client');
		Route::get('/scan/unit', 'ScannerController@unit')->name('scanner.unit');
		Route::get('/scan/update', 'ScannerController@updateOrder')->name('scanner.update');
		Route::get('/scan/order', 'ScannerController@order')->name('scanner.order');
		Route::get('/scan/create_order', 'ScannerController@createOrder')->name('scanner.create_order');
		Route::get('/scan/cancel_order', 'ScannerController@cancelOrder')->name('scanner.cancel_order');
		Route::get('/scan/promocode', 'ScannerController@promocode')->name('scanner.promocode');
		Route::get('/scan/pay', 'ScannerController@pay')->name('scanner.pay');
		Route::get('/scan/force_pay', 'ScannerController@forcePay')->name('scanner.force_pay');
		Route::get('/scan/pay_extra', 'ScannerController@payExtra')->name('scanner.pay_extra');
		Route::get('/scan/print_receipt', 'ScannerController@printReceipt')->name('scanner.print_receipt');
		Route::get('/scan/end', 'ScannerController@end')->name('scanner.end');
		Route::get('/scan/group', 'ScannerController@addToGroup')->name('scanner.add_to_group');
		Route::get('/scan/ungroup', 'ScannerController@removeFromGroup')->name('scanner.remove_from_group');
		Route::get('/scan/replace', 'ScannerController@replace')->name('scanner.replace');
		Route::get('/scan/get_clients', 'ScannerController@getClients')->name('scanner.get_clients');
		Route::get('/scan/update_condition', 'ScannerController@updateCondition')->name('scanner.update_condition');
	});

	Route::middleware('auth')->group(function () {

		Route::get('/', function () {
			return redirect()->route('dashboard.index');
		});

		Route::resource('roles', 'RoleController');
		Route::resource('permissions', 'PermissionController');

		Route::middleware('location_active')->group(function () {
			// вебкамера
			Route::post('webcam', 'ClientController@webcam')->name('client.webcam');
			Route::post('clients/webcam/{client}', 'ClientController@webcamSave')->name('client.webcam_save');

			Route::get('synchronizations', 'SynchronizationController@index')->name('synchronizations.index');

			// смены
			Route::get('shifts/{id}/report', 'ShiftController@report')->name('shifts.report');
			Route::get('shifts', 'ShiftController@index')->name('shifts.index');
			Route::get('shifts/open', 'ShiftController@open')->name('shifts.open');
			Route::get('shifts/xreport', 'ShiftController@xreport')->name('shifts.xreport');
			Route::get('shifts/{id}', 'ShiftController@close')->name('shifts.close');

			Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard.index');
			Route::get('analytics', 'DashboardController@analytics')->name('analytics.index');

			// настройки
			Route::get('settings', 'SettingsController@edit')->name('settings.edit');
			Route::post('settings', 'SettingsController@update')->name('settings.update');

			// категории
			Route::resource('categories', 'CategoryController');

			// бренды
			Route::resource('brands', 'BrandController');

			// крепления
			Route::resource('bindings', 'BindingController');

			// агенты
			Route::get('agents/{id}/restore', 'AgentController@restore')->name('agents.restore');
			Route::resource('agents', 'AgentController');

			// пользователи
			Route::get('users/{id}/restore', 'UserController@restore')->name('users.restore');
			Route::resource('users', 'UserController');
			Route::get('users/{id}/barcode', 'UserController@barcode')->name('users.barcode');

			// модели
			Route::resource('products', 'ProductController');

			// филиалы
			Route::resource('locations', 'LocationController');

			// прейскуранты
			Route::resource('price_lists', 'PriceListController');
			Route::post('price_lists/{price_list}/timeline', 'PriceListController@timeline')->name('price_lists.timeline');


			// клиенты
			Route::get('clients/json', 'ClientController@json')->name('clients.json');
			Route::resource('clients', 'ClientController');

			// заказы
			Route::resource('orders', 'OrderController');
			Route::get('orders/{order}/agreement', 'OrderController@agreement')->name('agreement');
			Route::get('orders/{order}/barcode', 'OrderController@barcode');
			Route::get('orders/{order}/sticker', 'OrderController@sticker');
			Route::get('orders/{order}/pledge', 'OrderController@pledgeAgreement');


			// склад
			Route::get('stock/json', 'StockController@json')->name('stock.json');
			Route::get('stock/import', 'StockController@import')->name('stock.import');
			Route::post('stock/import', 'StockController@import');
			Route::get('stock/is_unique', 'StockController@checkIfUnitUnique')->name('stock.is_unique');
			Route::resource('stock', 'StockController');

			// массовое редактирование
			Route::get('massediting', 'MassEditingController@index')->name('massediting.index');
			Route::post('massediting', 'MassEditingController@store')->name('massediting.store');
			Route::post('massediting/units', 'MassEditingController@getUnits')->name('massediting.get_units');
			Route::post('massediting/unit', 'MassEditingController@getUnit')->name('massediting.get_unit');

			// инвентаризация
			Route::get('stocktaking/perform', 'StocktakingController@perform')->name('stocktaking.perform');
			Route::get('stocktaking/{stocktaking}', 'StocktakingController@show')->name('stocktaking.show');
			Route::get('stocktaking', 'StocktakingController@index')->name('stocktaking.index');
			Route::post('stocktaking', 'StocktakingController@store')->name('stocktaking.store');
			Route::post('stocktaking/units', 'StocktakingController@getUnits')->name('stocktaking.get_units');
			Route::post('stocktaking/unit', 'StocktakingController@getUnit')->name('stocktaking.get_unit');

			// отчеты
			Route::get('reports/daily_revenue', 'ReportController@daily_revenue')->name('reports.financial');
			Route::get('reports/agreements', 'ReportController@agreements')->name('reports.agreements');
			Route::get('reports/agent_sales_common', 'ReportController@agent_sales_common')->name('reports.agent_sales_common');
			Route::get('reports/agent_sales_detailed', 'ReportController@agent_sales_detailed')->name('reports.agent_sales_detailed');

			Route::get('reports/inventory_rent', 'ReportController@inventory_rent')->name('reports.inventory_rent');
			Route::get('reports/inventory_stock', 'ReportController@inventory_stock')->name('reports.inventory_stock');
			Route::get('reports/inventory_stock_detailed', 'ReportController@inventory_stock_detailed')->name('reports.inventory_stock_detailed');
			Route::get('reports/inventory_sale', 'ReportController@inventory_sale')->name('reports.inventory_sale');
			Route::get('reports/inventory_history', 'ReportController@inventory_history')->name('reports.inventory_history');

			Route::get('reports/inventory_products', 'ReportController@inventory_products')->name('reports.inventory_products');
			Route::get('reports/products_sale', 'ReportController@products_sale')->name('reports.products_sale');
			Route::get('reports/bookings', 'ReportController@bookings')->name('reports.bookings');
			Route::get('reports/effectivity', 'ReportController@effectivity')->name('reports.effectivity');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use UploadImage;

class Client extends Model
{
	use \App\Traits\LocationIdentificator;
	public $incrementing = false;
	// protected $guarded = ['id'];

	protected $fillable = [
		'id',
		'user_id',
		'first_name',
		'last_name',
		'skill',
		'age',
		'mid_name',
		'phone',
		'email',
		'passport',
		'passport_status',
		'description',
		'birthday',
		'photo',
		'passport_scan',
		'is_signed',
		'created_at',
		'updated_at',
	];

	protected $appends = ['full_name', 'optional_id', 'images', 'birthday_short'];

	protected $dates = [
		'birthday',
		'created_at',
		'updated_at'
	];

	protected $casts = [
		'is_signed' => 'boolean'
	];

	/** constants **/

	const PASSPORT_STATUS_PENDING = 'pending';
	const PASSPORT_STATUS_VALID	  = 'valid';
	const PASSPORT_STATUS_INVALID = 'invalid';

	/** RELATIONS **/

	public function feature()
	{
		return $this->hasOne(ClientFeature::class);
	}

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function orders()
	{
		return $this->hasMany(Order::class);
	}

	public function currentOrder()
	{
		return $this->hasOne(Order::class)->active()->latest('id');
	}

	/** ATTRIBUTES **/

	public function getFullNameAttribute()
	{
		$fullName = $this->last_name . ' ' . $this->first_name;
		if ($this->mid_name) {
			$fullName .= ' ' . $this->mid_name;
		}

		return $fullName;
	}

	public function getAgeAttribute($value)
	{
		return $value ?? ($this->birthday ? $this->birthday->diffInYears(\Carbon\Carbon::now()) : null);
	}

	public function getBirthdayShortAttribute()
	{
		return $this->birthday ? $this->birthday->format('d.m.Y') : '';
	}

	public function getOptionalIdAttribute()
	{
		return 'L' . sprintf("%06d", $this->id);
	}

	public function getZNumAttribute()
	{
		$weights = [13, 17, 21, 25, 30, 35, 41, 48, 57, 66, 78, 94, 200];
		$heights = [0, 0, 0, 0, 0, 0, 0, 0, 157, 166, 178, 194, 250];
		$sizes = [
			250 => ['0.75', '1', '1.5', '1.75', '2.25', '2.75', '3.5', '', '', '', '', '', '', ''],
			270 => ['0.75', '1', '1.25', '1.5', '2', '2.5', '3', '3.5', '4.5', '5.5', '6.5', '7.5', '', ''],
			290 => ['', '0.75', '1', '1.5', '1.75', '2.25', '2.75', '3', '4', '5', '6', '7', '8.5', '10'],
			310 => ['', '', '', '1.25', '1.5', '2', '2.5', '3', '3.5', '4.5', '5.5', '6.5', '8', '9.5'],
			330 => ['', '', '', '', '1.5', '1.75', '2.25', '2.75', '3.5', '4', '5', '6', '7', '8.5'],
			600 => ['', '', '', '', '', '1.75', '2', '2.5', '3', '3.5', '4.5', '5.5', '6.5', '8']
		];

		// длина подошвы
		// $feet_length = 310;
		// $this->feature->shoe_size
		$shoe_size = $this->feature->shoe_size;
		$feet_length = (20 / 3) * ($shoe_size - 2);

		if (
			$this->feature()->exists()
			&& $this->feature->weight
			&& $this->feature->height
			&& $this->feature->shoe_size
		) {
			foreach ($weights as $w_key => $weight)
				if ($this->feature->weight <= $weight) break;

			foreach ($heights as $h_key => $height)
				if ($this->feature->height <= $height) break;

			foreach ($sizes as $size => $znums)
				if ($feet_length <= $size) break;

			$znum = $znums[min($w_key, $h_key)];
		} else $znum = '100';

		return $znum;
	}

	public function getUpdatedAtAttribute($value)
	{
		return \Carbon\Carbon::parse($value)->format('H:i d.m.Y');
	}

	public function getCreatedAtAttribute($value)
	{
		return \Carbon\Carbon::parse($value)->format('H:i d.m.Y');
	}

	public function getInGroupAttribute()
	{
		return $this->orders()->active()->whereNotNull('group_id')->count() > 0;
	}

	public function getImagesAttribute()
	{
		if ($this->passport_scan) {
			if (strpos($this->passport_scan, 'http://') !== false || strpos($this->passport_scan, 'https://') !== false) {
				$passport = $this->passport_scan;
			} else {
				$passport = asset(UploadImage::load('passport') . $this->passport_scan);
			}
		} else {
			$passport = '';
		}

		if ($this->photo) {
			if (strpos($this->photo, 'http://') !== false || strpos($this->photo, 'https://') !== false) {
				$photo = $this->photo;
			} else {
				$photo = asset(UploadImage::load('client') . $this->photo);
			}
		} else {
			$photo = '';
		}

		return [
			'passport' => $passport,
			'photo' => $photo,
		];
	}
}

app/Http/Controllers/Instructors/ClientController.php
<?php

namespace App\Http\Controllers\Instructors;

use App\Http\Controllers\Controller;
use App\Instructors\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;

class ClientController extends Controller
{
	public function __construct()
	{
		$this->middleware(['role:superadmin|admin|manager|operator']);
	}

	public function index()
	{
		return view('instructors.clients.index');
	}

	public function clients_json(Request $request)
	{
		$columns = Schema::getColumnListing('clients');

		$clients = Client::where([])
						->orderBy(
							$columns[$request->order[0]['column']],
							$request->order[0]['dir']
						);


		if ($request->search['value'] !== null)
		{
			foreach ($columns as $column)
				$clients->orWhere($column, 'like', '%'.$request->search['value'].'%');
		}

        $filteredCount = $clients->count();
        
		$clients = $clients->offset($request->start)
            ->limit($request->length)
            ->get();

		$output = [];

		foreach ($clients as $client)
		{
			$output[] = [
				$client->id,
				$client->last_name.' '.$client->first_name.' '.$client->mid_name,
				$client->phone,
				$client->email,
				$client->created_at->format('d.m.Y H:i'),
				$client->updated_at->format('d.m.Y H:i')
			];
		}

		return json_encode([
			'draw' => $request->draw,
			'recordsTotal' => Client::count(),
			'recordsFiltered' => $filteredCount,
			'data' => $output
		]);
	}

	public function create()
	{
		return view('instructors.clients.create');
	}

	public function store(Request $request)
	{
		request()->validate([
			'last_name'   => 'required|string|max:50',
			'first_name'  => 'required|string|max:50',
			'mid_name'    => 'required|string|max:50'
		]);

		$client = Client::create($request->except('ajax'));

		if($request->ajax)
		{
			return response()->json([
				'success' => true,
				'name' => $client->full_name,
				'id' => $client->id
			]);
		}
		return redirect()->route('instructors.clients.index', $client)
			->with('success', 'Клиент успешно добавлен');
	}

	public function show()
	{
		//
	}

	public function edit(Client $client)
	{
		return view('instructors.clients.edit', compact('client'));
	}

	public function update(Request $request, Client $client)
	{
		request()->validate([
			'last_name'   => 'required|string|max:50',
			'first_name'  => 'required|string|max:50',
			'mid_name'    => 'required|string|max:50'
		]);

		$client->update($request->all());

		return redirect()->route('instructors.clients.index', $client)
			->with('success', 'Данные успешно сохранены');
	}

	public function destroy(Client $client)
	{
		$client->delete();

		return redirect()->route('instructors.clients.index')->with('success', 'Клиент удален');
	}
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')

@include('common.validation')
@include('common.notifications')

@push('js')
<script type="text/javascript">
	$('#checkPassport').click(function () {
		$.ajax({
            'url': "{{ route('expired_passports.check') }}",
            'type': 'POST',
            'data': {
            	data: $('#passport').val()
            },
            'success': function(data) {
                if(data.success)
                {
                	swal({
				        title: 'Успешно',
				        text: 'Данные паспорта отсутствуют в базе просроченных паспортов',
				        type: 'success',
				        button: {
							text: "Продолжить",
							value: true,
							visible: true,
							className: "btn btn-primary"
				        }
				    });
                }
                else
                {
                	swal({
				        title: 'Внимание!',
				        text: 'Данные паспорта находятся в базе просроченных паспортов',
				        type: 'error',
				        button: {
							text: "Продолжить",
							value: true,
							visible: true,
							className: "btn btn-primary"
				        }
				    });
                }
            },
            'error': function(){
                console.error('Something wrong!');
            }
        });
	});
</script>
@endpush

<div class="card">

	<div class="card-header">
		<a href="{{ route('clients.index') }}" class="btn btn-light">
			<i class="fa fa-angle-left"></i>Назад</a>
	</div>

	<div class="card-body">
		<h4 class="card-title">Новый клиент</h4>
		<form method="post" action="{{ route('clients.store') }}" enctype="multipart/form-data">
			@csrf

		<div class="row">
			<div class="col-md-10">

		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<label>Фамилия</label>
					<input type="text" class="form-control" name="last_name" required autofocus>
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label>Имя</label>
					<input type="text" class="form-control" name="first_name" required>
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label>Отчество</label>
					<input type="text" class="form-control" name="mid_name">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label>Номер телефона</label>
					<input type="text" class="form-control" name="phone">
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<label>E-mail</label>
					<input type="email" class="form-control" name="email">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label>Номер паспорта</label>

					<div class="input-group col-xs-12">
                        <input type="text" class="form-control passport" name="passport" id="passport">
                        <span class="input-group-append">
                         	<button class="file-upload-browse btn btn-info" type="button" id="checkPassport">Проверить</button>
                        </span>
                    </div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<label>Дата рождения</label>
					<input type="text" class="form-control date" name="birthday">
				</div>
			</div>
		</div>

		<div class="form-group">
			<label>Заметка</label>
			<textarea class="form-control" name="description"></textarea>
		</div>

		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<label>Вес</label>
					<input type="text" class="form-control" name="weight">
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label>Рост</label>
					<input type="text" class="form-control" name="height">
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label>Размер обуви</label>
					<input type="text" class="form-control" name="shoe_size">
				</div>
			</div>
		</div>

		<div class="form-group">
			<label>
				<input type="checkbox" name="is_signed" value="1">
				Договор подписан
			</label>
		</div>

			</div>
			<div class="col-md-2">

				<div class="form-group">
					<label>Фото</label>
					<input type="file" class="dropify" name="file_photo">
				</div>

				<div class="form-group">
					<label>Скан паспорта</label>
					<input type="file" class="dropify" name="file_passport">
				</div>

			</div>
		</div>

		<button type="submit" class="btn btn-success">
			<i class="fa fa-save"></i>Сохранить</button>

		</form>
	</div>

</div>

<script>
(function($) {
	'use strict';
	$(".date").inputmask("dd.mm.yyyy", {"placeholder": "дд.мм.гггг"});
	$(".passport").inputmask("9999 999999");
	$('.dropify').dropify();
})(jQuery);
</script>

@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')

@include('common.validation')
@include('common.notifications')

<div class="card">

	<div class="card-header">
		<a href="{{ route('clients.create') }}" class="btn btn-success">
			<i class="fa fa-plus"></i>Добавить клиента</a>
	</div>

	<div class="card-body">
		<h4 class="card-title">Клиенты</h4>

		<div class="row">
		<div class="col-12">
			<table id="client-listing" class="table">
			<thead>
				<tr>
					<th>ID</th>
					<th>ФИО</th>
					<th>Телефон</th>
					<th>Email</th>
					<th>Дата создания</th>
					<th>Дата изменения</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
			</table>
		</div>
		</div>
	</div>

</div>

<script>
(function($) {
'use strict';
$(function() {
	var table = $('#client-listing').DataTable({
		"processing": true,
		"serverSide": true,
		"ajax": "{{ route('clients.json') }}",
		"iDisplayLength": 25,
		"aaSorting": [[0, "desc"]],
		"language": {
			"lengthMenu": "Показывать _MENU_ записей на странице",
			"zeroRecords": "Записей не найдено",
			"loadingRecords": "Загрузка... может занять несколько секунд...",
			"info": "Страница _PAGE_ из _PAGES_",
			"infoEmpty": "Показано с 0 по 0 из 0 записей",
			"search": "",
			"infoFiltered": "(Найдено записей: _TOTAL_)",
			"sInfo": "Показано с _START_ по _END_ из _TOTAL_ записей",
			"paginate":
			{
				"first":    "Первая",
				"last":     "Последняя",
				"next":     "Следующая",
				"previous": "Предыдущая"
			}
		},
		"pageLength": {{ Request::get('length') ? Request::get('length') : 10 }},
			initComplete: function () {
      			setTimeout(function () {
        				table.page({{ Request::get('page') ? Request::get('page') - 1 : 0 }})
							.draw(false);
      			}, 10);
    		},
			"drawCallback": function( settings ) {
				var page = Math.ceil(settings._iDisplayStart / settings._iDisplayLength) + 1;

				updateUrlParameter('page', page);
				updateUrlParameter('length', settings._iDisplayLength);
			}
	});
	$('#client-listing').each(function() {
		var datatable = $(this);
		var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
		search_input.attr('placeholder', 'Поиск');
		search_input.removeClass('form-control-sm');
		var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
		length_sel.removeClass('form-control-sm');
	});
	$('#client-listing tbody').on('click', 'tr', function () {
		var id = $('td', this).eq(0).text();
		$(location).attr('href','/clients/'+parseInt(id.replace(/[^-0-9]/gim, ''))+'/edit');
	});
});
})(jQuery);
</script>

@endsection

resources/views/clients/show.blade.php
@extends('layouts.app')

@section('content')

@include('common.validation')
@include('common.notifications')

<div class="card">
	<div class="card-header">
		<a href="{{ route('clients.index') }}" class="btn btn-light"><i class="fa fa-angle-left"></i>Назад</a>
	</div>
	<div class="card-body">
		<h4 class="card-title">Карточка клиента</h4>
		<table class="table">
			<tbody>
				<tr>
					<td>
						Имя
					</td>
					<td>
						{{ $client->full_name }}
					</td>
				</tr>
				<tr>
					<td>
						Номер телефона
					</td>
					<td>
						{{ $client->phone }}
					</td>
				</tr>
				<tr>
					<td>
						Email
					</td>
					<td>
						{{ $client->email }}
					</td>
				</tr>
				<tr>
					<td>
						Номер паспорта
					</td>
					<td>
						{{ $client->passport }}
					</td>
				</tr>
				<tr>
					<td>
						Заметка
					</td>
					<td>
						{{ $client->description }}
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

@endsection